services:
  web:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5175:5175"
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    command: sh -lc "npm run dev"
volumes:
  node_modules:
